#include "RTFuncs.h"

PFN_vkGetRayTracingShaderGroupHandlesKHR RTFuncs::vkGetRayTracingShaderGroupHandlesKHR;
PFN_vkCmdTraceRaysKHR RTFuncs::vkCmdTraceRaysKHR;
PFN_vkCreateRayTracingPipelinesKHR RTFuncs::vkCreateRayTracingPipelinesKHR;
PFN_vkGetAccelerationStructureBuildSizesKHR RTFuncs::vkGetAccelerationStructureBuildSizesKHR;
PFN_vkCreateAccelerationStructureKHR RTFuncs::vkCreateAccelerationStructureKHR;
PFN_vkCmdBuildAccelerationStructuresKHR RTFuncs::vkCmdBuildAccelerationStructuresKHR;
PFN_vkGetAccelerationStructureDeviceAddressKHR RTFuncs::vkGetAccelerationStructureDeviceAddressKHR;
PFN_vkDestroyAccelerationStructureKHR RTFuncs::vkDestroyAccelerationStructureKHR;